# Generated by Django 3.0.3 on 2021-12-02 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(default='', max_length=500)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_desc', models.TextField(max_length=8000)),
                ('desc', models.CharField(default='', max_length=300)),
                ('hyp_link', models.CharField(default='', max_length=100)),
                ('hyp_text', models.CharField(default='', max_length=100)),
                ('meta_Title', models.CharField(default='', max_length=200)),
                ('slug_url', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('blog_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade_Title', models.CharField(default='', max_length=100)),
                ('info', models.CharField(default='', max_length=3000)),
                ('Grade_math', models.CharField(default='', max_length=3000)),
                ('Grade_Science', models.CharField(default='', max_length=3000)),
                ('Grade_English', models.CharField(default='', max_length=3000)),
                ('Grade_SST', models.CharField(default='', max_length=3000)),
                ('desc', models.CharField(default='', max_length=200)),
                ('Title', models.CharField(default='', max_length=100)),
                ('GId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade_Title', models.CharField(default='', max_length=100)),
                ('info', models.CharField(default='', max_length=3000)),
                ('Math', models.CharField(default='', max_length=3000)),
                ('Eco', models.CharField(default='', max_length=3000)),
                ('Accounts', models.CharField(default='', max_length=3000)),
                ('BST', models.CharField(default='', max_length=3000)),
                ('English', models.CharField(default='', max_length=3000)),
                ('desc', models.CharField(default='', max_length=200)),
                ('Title', models.CharField(default='', max_length=100)),
                ('GId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Humanities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade_Title', models.CharField(default='', max_length=100)),
                ('info', models.CharField(default='', max_length=3000)),
                ('PolSc', models.CharField(default='', max_length=3000)),
                ('Geo', models.CharField(default='', max_length=3000)),
                ('History', models.CharField(default='', max_length=3000)),
                ('Sociology', models.CharField(default='', max_length=3000)),
                ('Psycology', models.CharField(default='', max_length=3000)),
                ('English', models.CharField(default='', max_length=3000)),
                ('desc', models.CharField(default='', max_length=200)),
                ('Title', models.CharField(default='', max_length=100)),
                ('GId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade_Title', models.CharField(default='', max_length=100)),
                ('info', models.CharField(default='', max_length=3000)),
                ('Math', models.CharField(default='', max_length=3000)),
                ('Chemistry', models.CharField(default='', max_length=3000)),
                ('Physics', models.CharField(default='', max_length=3000)),
                ('Bio', models.CharField(default='', max_length=3000)),
                ('English', models.CharField(default='', max_length=3000)),
                ('desc', models.CharField(default='', max_length=200)),
                ('Title', models.CharField(default='', max_length=100)),
                ('GId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=10)),
                ('Class', models.IntegerField(choices=[(6, 'Grade 6th'), (7, 'Grade 7th'), (8, 'Grade 8th'), (9, 'Grade 9th'), (10, 'Grade 10th'), (11, 'Grade 11th'), (12, 'Grade 12th')])),
                ('Course', models.CharField(max_length=30)),
                ('Information', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=50)),
                ('School', models.CharField(blank=True, default='', max_length=100)),
                ('Mother_Name', models.CharField(blank=True, default='', max_length=50)),
                ('Father_Name', models.CharField(blank=True, default='', max_length=50)),
                ('Father_Occupation', models.CharField(blank=True, default='', max_length=100)),
                ('Student_Phone_No', models.CharField(blank=True, default='', max_length=10)),
                ('Father_Phone_No', models.CharField(blank=True, default='', max_length=10)),
                ('Mother_Phone_No', models.CharField(blank=True, default='', max_length=10)),
                ('Email_Id', models.CharField(blank=True, default='', max_length=50)),
                ('Class', models.CharField(blank=True, default='', max_length=10)),
                ('Subject', models.CharField(blank=True, default='', max_length=100)),
                ('Timings', models.CharField(blank=True, default='', max_length=100)),
                ('Address', models.CharField(blank=True, default='', max_length=100)),
                ('Carrier_interest', models.CharField(blank=True, default='', max_length=50)),
                ('Fees', models.CharField(blank=True, default='', max_length=10)),
                ('Comment', models.CharField(blank=True, default='', max_length=1000)),
                ('Referal', models.CharField(blank=True, default='', max_length=10)),
                ('counseling', models.CharField(blank=True, default='', max_length=10)),
                ('conversion', models.CharField(blank=True, default='', max_length=1000)),
                ('leadVia', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Study_Class',
            fields=[
                ('classid', models.CharField(default='Null', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=10)),
                ('Class', models.IntegerField(choices=[(6, 'Grade 6th'), (7, 'Grade 7th'), (8, 'Grade 8th'), (9, 'Grade 9th'), (10, 'Grade 10th'), (11, 'Grade 11th'), (12, 'Grade 12th')])),
                ('Course', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=200)),
                ('Education', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=200)),
                ('Thoughts', models.CharField(max_length=100)),
                ('Query', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_name', models.CharField(max_length=100)),
                ('mock_desc', models.CharField(default='abc', max_length=8000)),
                ('ass_desc', models.CharField(default='abc', max_length=8000)),
                ('book_desc', models.CharField(default='abc', max_length=8000)),
                ('sol_desc', models.CharField(default='abc', max_length=8000)),
                ('sub', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.Study_Class')),
            ],
        ),
        migrations.CreateModel(
            name='chap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(default='abc', max_length=500)),
                ('mock_desc', models.CharField(default='abc', max_length=8000)),
                ('ass_desc', models.CharField(default='abc', max_length=8000)),
                ('book_desc', models.CharField(default='abc', max_length=8000)),
                ('sol_desc', models.CharField(default='abc', max_length=8000)),
                ('chap_name', models.CharField(max_length=100)),
                ('Book_url', models.CharField(default='abc', max_length=500)),
                ('Sol_url', models.CharField(default='abc', max_length=500)),
                ('Mock_url', models.CharField(default='abc', max_length=500)),
                ('Ass_url', models.CharField(default='abc', max_length=500)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.subject')),
            ],
        ),
    ]
