# Generated by Django 3.0.3 on 2021-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='url_ass',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='url_books',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='url_mock',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='url_sol',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
