# Generated by Django 3.0.1 on 2021-12-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20211201_1535'),
        ('webpages', '0002_auto_20211202_2019'),
    ]

    operations = [
    ]
